// Generated by mcp/scripts/bundle.mjs — edit mcp/src/http, not this file.

// src/http/handler.ts
import { createClient } from "npm:@supabase/supabase-js@2";

// src/http/oauth.ts
var TOKEN_TTL_SECONDS = 60 * 60 * 24 * 30;
var CODE_TTL_SECONDS = 60 * 5;
function protectedResourceMetadata(base) {
  return {
    resource: base,
    authorization_servers: [base],
    bearer_methods_supported: ["header"],
    scopes_supported: ["cartographer"]
  };
}
function authorizationServerMetadata(base) {
  return {
    issuer: base,
    authorization_endpoint: `${base}/authorize`,
    token_endpoint: `${base}/token`,
    registration_endpoint: `${base}/register`,
    scopes_supported: ["cartographer"],
    response_types_supported: ["code"],
    grant_types_supported: ["authorization_code"],
    // PKCE is not optional here: it is the only thing binding the code to the
    // client that asked for it.
    code_challenge_methods_supported: ["S256"],
    token_endpoint_auth_methods_supported: ["client_secret_post", "none"]
  };
}
var B64URL = (bytes) => {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
};
function randomToken(bytes = 32) {
  return B64URL(crypto.getRandomValues(new Uint8Array(bytes)));
}
async function sha256Base64Url(input) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(input));
  return B64URL(new Uint8Array(digest));
}
async function pkceMatches(challenge, verifier) {
  if (!challenge || !verifier) return false;
  return await sha256Base64Url(verifier) === challenge;
}
function redirectAllowed(registered, wanted) {
  return registered.includes(wanted);
}
function redirectWithCode(redirectUri, code, state) {
  const url = new URL(redirectUri);
  url.searchParams.set("code", code);
  if (state) url.searchParams.set("state", state);
  return url.toString();
}
function redirectWithError(redirectUri, error, state) {
  const url = new URL(redirectUri);
  url.searchParams.set("error", error);
  if (state) url.searchParams.set("state", state);
  return url.toString();
}

// src/rows.ts
function newId(prefix) {
  return prefix + Math.random().toString(36).slice(2, 8);
}
var CARD_W = 244;
var CARD_H = 116;

// src/fields.ts
function effectiveFields(page, type) {
  return page.custom !== null ? page.custom : type?.fields ?? [];
}
function resolveFieldKey(fields, wanted) {
  const want = wanted.trim().toLowerCase();
  for (const f of fields) if (f.key.toLowerCase() === want) return f.key;
  for (const f of fields) if (f.label.trim().toLowerCase() === want) return f.key;
  return null;
}
function labelledFields(page, type) {
  const out = {};
  for (const field of effectiveFields(page, type)) {
    if (field.kind === "heading") continue;
    const value = page.fields[field.key];
    if (value) out[field.label] = value;
  }
  return out;
}
function mapFieldValues(fields, input) {
  const values = {};
  const missing = [];
  for (const [name, value] of Object.entries(input)) {
    const key = resolveFieldKey(fields, name);
    if (key === null) missing.push(name);
    else values[key] = value;
  }
  return { values, unknown: missing };
}

// src/tools.ts
var ToolError = class extends Error {
};
function str(args, key, fallback) {
  const v = args[key];
  if (typeof v === "string" && v.trim()) return v.trim();
  if (fallback !== void 0) return fallback;
  throw new ToolError(`"${key}" is required.`);
}
function optionalStr(args, key) {
  const v = args[key];
  return typeof v === "string" && v.trim() ? v.trim() : void 0;
}
function strings(args, key) {
  const v = args[key];
  if (!Array.isArray(v)) return void 0;
  return v.filter((x) => typeof x === "string").map((s) => s.trim()).filter(Boolean);
}
function record(args, key) {
  const v = args[key];
  if (!v || typeof v !== "object" || Array.isArray(v)) return void 0;
  const out = {};
  for (const [k, value] of Object.entries(v)) {
    out[k] = typeof value === "string" ? value : String(value);
  }
  return out;
}
async function take(query) {
  const { data, error } = await query;
  if (error) throw new ToolError(error.message);
  return data ?? [];
}
async function resolveProject(db, args) {
  const projects = await take(db.from("projects").select("*"));
  if (!projects.length) throw new ToolError("There are no projects in this account yet.");
  const wanted = optionalStr(args, "project");
  if (!wanted) {
    if (projects.length === 1) return projects[0];
    throw new ToolError(
      `Several projects exist \u2014 say which: ${projects.map((p) => p.name).join(", ")}.`
    );
  }
  const low = wanted.toLowerCase();
  const hit = projects.find((p) => p.id === wanted) ?? projects.find((p) => p.name.toLowerCase() === low) ?? projects.find((p) => p.name.toLowerCase().includes(low));
  if (!hit) throw new ToolError(`No project called "${wanted}". There is: ${projects.map((p) => p.name).join(", ")}.`);
  return hit;
}
async function resolvePage(db, projectId, wanted) {
  const pages = await take(db.from("pages").select("*").eq("project_id", projectId));
  const byId = pages.find((p) => p.id === wanted);
  if (byId) return byId;
  const low = wanted.trim().toLowerCase();
  const exact = pages.filter((p) => p.title.trim().toLowerCase() === low);
  if (exact.length === 1) return exact[0];
  if (exact.length > 1) {
    throw new ToolError(`"${wanted}" names ${exact.length} pages. Use the id: ${exact.map((p) => p.id).join(", ")}.`);
  }
  const loose = pages.filter((p) => p.title.toLowerCase().includes(low));
  if (loose.length === 1) return loose[0];
  if (loose.length > 1) {
    throw new ToolError(`"${wanted}" could be: ${loose.slice(0, 8).map((p) => p.title).join(", ")}.`);
  }
  throw new ToolError(`No page called "${wanted}" in this project.`);
}
function typeOf(project, key) {
  return project.types?.[key];
}
function resolveType(project, wanted) {
  const types = project.types ?? {};
  if (!wanted) return types["blank"] ? "blank" : Object.keys(types)[0] ?? "blank";
  const low = wanted.trim().toLowerCase();
  if (types[wanted]) return wanted;
  for (const [key, t] of Object.entries(types)) {
    if (key.toLowerCase() === low || t.label.trim().toLowerCase() === low) return key;
  }
  throw new ToolError(
    `No block type "${wanted}". This project has: ${Object.values(types).map((t) => t.label).join(", ")}.`
  );
}
function freeSpot(onBoard) {
  if (!onBoard.length) return { x: 120, y: 120 };
  const lowest = Math.max(...onBoard.map((p) => p.y + (p.h || CARD_H)));
  return { x: 120, y: lowest + 84 };
}
var now = () => Date.now();
var listProjects = {
  name: "list_projects",
  title: "List projects",
  description: "Every project in this account, with how much is in each. Start here when you do not know what exists.",
  inputSchema: { type: "object", properties: {} },
  writes: false,
  run: async (db) => {
    const [projects, pages] = await Promise.all([
      take(db.from("projects").select("*")),
      take(db.from("pages").select("id,project_id"))
    ]);
    return projects.map((p) => ({
      id: p.id,
      name: p.name,
      system: p.system === "Untitled" ? null : p.system,
      pages: pages.filter((page) => page.project_id === p.id).length
    }));
  }
};
var describeProject = {
  name: "describe_project",
  title: "Describe a project",
  description: "The whole shape of a project in one call: its areas and the boards inside them, every block type with the fields it defines, and the tags in use. Read this before creating or editing anything \u2014 it is what tells you which board a page can go on, which types exist, and what fields they carry.",
  inputSchema: {
    type: "object",
    properties: {
      project: { type: "string", description: "Project name or id. Optional when there is only one." }
    }
  },
  writes: false,
  run: async (db, args) => {
    const project = await resolveProject(db, args);
    const [areas, boards, pages] = await Promise.all([
      take(db.from("areas").select("*").eq("project_id", project.id)),
      take(db.from("boards").select("*").eq("project_id", project.id)),
      take(db.from("pages").select("*").eq("project_id", project.id))
    ]);
    const tags = /* @__PURE__ */ new Set();
    for (const page of pages) for (const tag of page.tags ?? []) tags.add(tag);
    return {
      id: project.id,
      name: project.name,
      system: project.system === "Untitled" ? null : project.system,
      areas: areas.map((area) => ({
        id: area.id,
        name: area.name,
        defaultType: area.default_type,
        boards: boards.filter((b) => b.area_id === area.id).map((b) => ({
          id: b.id,
          name: b.name,
          pages: pages.filter((p) => p.board_id === b.id).length
        }))
      })),
      blockTypes: Object.entries(project.types ?? {}).filter(([, t]) => !t.hidden).map(([key, t]) => ({
        key,
        label: t.label,
        fields: t.fields.map((f) => ({
          label: f.label,
          kind: f.kind,
          ...f.options ? { choices: f.options } : {}
        }))
      })),
      tagsInUse: [...tags].sort()
    };
  }
};
var listPages = {
  name: "list_pages",
  title: "List pages",
  description: "Pages in a project, optionally narrowed to one board, one block type, or one tag. Returns titles and ids rather than whole pages \u2014 follow up with read_page for the ones you want.",
  inputSchema: {
    type: "object",
    properties: {
      project: { type: "string", description: "Project name or id. Optional when there is only one." },
      board: { type: "string", description: "Board name or id." },
      type: { type: "string", description: 'Block type label or key, e.g. "Creature".' },
      tag: { type: "string", description: "Only pages carrying this tag." }
    }
  },
  writes: false,
  run: async (db, args) => {
    const project = await resolveProject(db, args);
    const [boards, pages] = await Promise.all([
      take(db.from("boards").select("*").eq("project_id", project.id)),
      take(db.from("pages").select("*").eq("project_id", project.id))
    ]);
    const boardName = optionalStr(args, "board");
    const board = boardName ? boards.find((b) => b.id === boardName) ?? boards.find((b) => b.name.toLowerCase() === boardName.toLowerCase()) : void 0;
    if (boardName && !board) {
      throw new ToolError(`No board called "${boardName}". There is: ${boards.map((b) => b.name).join(", ")}.`);
    }
    const typeKey = optionalStr(args, "type") ? resolveType(project, optionalStr(args, "type")) : void 0;
    const tag = optionalStr(args, "tag")?.toLowerCase();
    return pages.filter((p) => (!board || p.board_id === board.id) && (!typeKey || p.type === typeKey) && (!tag || (p.tags ?? []).some((t) => t.toLowerCase() === tag))).map((p) => ({
      id: p.id,
      title: p.title,
      type: typeOf(project, p.type)?.label ?? p.type,
      board: boards.find((b) => b.id === p.board_id)?.name ?? p.board_id,
      tags: p.tags ?? []
    }));
  }
};
var readPage = {
  name: "read_page",
  title: "Read a page",
  description: "One page in full: its field values by label, its body, its tags, and the pages it links to and from.",
  inputSchema: {
    type: "object",
    properties: {
      page: { type: "string", description: "Page title or id." },
      project: { type: "string", description: "Project name or id. Optional when there is only one." }
    },
    required: ["page"]
  },
  writes: false,
  run: async (db, args) => {
    const project = await resolveProject(db, args);
    const page = await resolvePage(db, project.id, str(args, "page"));
    const [edges, pages] = await Promise.all([
      take(db.from("edges").select("*").eq("project_id", project.id)),
      take(db.from("pages").select("id,title").eq("project_id", project.id))
    ]);
    const title = (id) => pages.find((p) => p.id === id)?.title ?? id;
    return {
      id: page.id,
      title: page.title,
      type: typeOf(project, page.type)?.label ?? page.type,
      tags: page.tags ?? [],
      fields: labelledFields(page, typeOf(project, page.type)),
      body: page.body,
      linksTo: edges.filter((e) => e.from_page === page.id).map((e) => title(e.to_page)),
      linkedFrom: edges.filter((e) => e.to_page === page.id).map((e) => title(e.from_page))
    };
  }
};
var searchPages = {
  name: "search",
  title: "Search a project",
  description: "Find pages by any text written on them \u2014 title, tags, field values or body. Case-insensitive substring, the same match the app's own search box uses.",
  inputSchema: {
    type: "object",
    properties: {
      query: { type: "string", description: "What to look for." },
      project: { type: "string", description: "Project name or id. Optional when there is only one." }
    },
    required: ["query"]
  },
  writes: false,
  run: async (db, args) => {
    const project = await resolveProject(db, args);
    const q = str(args, "query").toLowerCase();
    const pages = await take(db.from("pages").select("*").eq("project_id", project.id));
    const hits = [];
    for (const page of pages) {
      const type = typeOf(project, page.type);
      const at = (text) => text.toLowerCase().indexOf(q);
      const excerpt = (text, i) => text.slice(Math.max(0, i - 40), i + q.length + 40).replace(/\s+/g, " ").trim();
      const inTitle = at(page.title);
      if (inTitle >= 0) {
        hits.push({ id: page.id, title: page.title, where: "title", excerpt: page.title });
        continue;
      }
      const tag = (page.tags ?? []).find((t) => t.toLowerCase().includes(q));
      if (tag) {
        hits.push({ id: page.id, title: page.title, where: "tag", excerpt: tag });
        continue;
      }
      let found = false;
      for (const field of effectiveFields(page, type)) {
        const value = page.fields[field.key];
        const i = value ? at(value) : -1;
        if (i >= 0) {
          hits.push({ id: page.id, title: page.title, where: field.label, excerpt: excerpt(value, i) });
          found = true;
          break;
        }
      }
      if (found) continue;
      const inBody = at(page.body);
      if (inBody >= 0) hits.push({ id: page.id, title: page.title, where: "body", excerpt: excerpt(page.body, inBody) });
    }
    return hits;
  }
};
var createPage = {
  name: "create_page",
  title: "Create a page",
  description: "Add a page to a board. Name the board and the block type as they appear in describe_project. Field values are given by label. The page appears in the app on its next sync.",
  inputSchema: {
    type: "object",
    properties: {
      title: { type: "string", description: "The page title." },
      board: { type: "string", description: "Board name or id to put it on." },
      type: { type: "string", description: 'Block type label, e.g. "Creature". Defaults to a blank page.' },
      body: { type: "string", description: "Markdown body. [[Page Title]] links to another page." },
      fields: { type: "object", description: 'Field values keyed by label, e.g. {"Hit points": "31"}.' },
      tags: { type: "array", items: { type: "string" }, description: "Tags to carry." },
      project: { type: "string", description: "Project name or id. Optional when there is only one." }
    },
    required: ["title", "board"]
  },
  writes: true,
  run: async (db, args) => {
    const project = await resolveProject(db, args);
    const boards = await take(db.from("boards").select("*").eq("project_id", project.id));
    const wanted = str(args, "board");
    const board = boards.find((b) => b.id === wanted) ?? boards.find((b) => b.name.toLowerCase() === wanted.toLowerCase()) ?? boards.find((b) => b.name.toLowerCase().includes(wanted.toLowerCase()));
    if (!board) {
      throw new ToolError(`No board called "${wanted}". There is: ${boards.map((b) => b.name).join(", ")}.`);
    }
    const typeKey = resolveType(project, optionalStr(args, "type"));
    const type = typeOf(project, typeKey);
    const given = record(args, "fields") ?? {};
    const { values, unknown } = mapFieldValues(type?.fields ?? [], given);
    const onBoard = await take(db.from("pages").select("*").eq("board_id", board.id));
    const at = freeSpot(onBoard);
    const row = {
      id: newId("n"),
      project_id: project.id,
      board_id: board.id,
      type: typeKey,
      title: str(args, "title"),
      x: at.x,
      y: at.y,
      w: CARD_W,
      h: CARD_H,
      fields: values,
      custom: null,
      cols: 0,
      body: optionalStr(args, "body") ?? "",
      tags: strings(args, "tags") ?? [],
      images: [],
      header: null,
      updated: now()
    };
    await take(db.from("pages").insert(row).select());
    return {
      created: { id: row.id, title: row.title, type: type?.label ?? typeKey, board: board.name },
      ...unknown.length ? { warning: `These named no field on a ${type?.label ?? typeKey} and were not written: ${unknown.join(", ")}.` } : {}
    };
  }
};
var updatePage = {
  name: "update_page",
  title: "Update a page",
  description: "Change a page. Only what you pass is touched \u2014 omit a property to leave it as it is. Field values given by label are merged into the existing ones; tags replace the list wholesale.",
  inputSchema: {
    type: "object",
    properties: {
      page: { type: "string", description: "Page title or id." },
      title: { type: "string", description: "A new title." },
      body: { type: "string", description: "Replaces the markdown body." },
      append: { type: "string", description: "Markdown added to the end of the body instead of replacing it." },
      fields: { type: "object", description: "Field values keyed by label; merged, not replaced." },
      tags: { type: "array", items: { type: "string" }, description: "Replaces the tag list." },
      project: { type: "string", description: "Project name or id. Optional when there is only one." }
    },
    required: ["page"]
  },
  writes: true,
  run: async (db, args) => {
    const project = await resolveProject(db, args);
    const page = await resolvePage(db, project.id, str(args, "page"));
    const type = typeOf(project, page.type);
    const patch = { updated: now() };
    const title = optionalStr(args, "title");
    if (title) patch.title = title;
    const body = typeof args["body"] === "string" ? args["body"] : void 0;
    const append = optionalStr(args, "append");
    if (body !== void 0) patch.body = body;
    if (append) patch.body = `${body ?? page.body}${(body ?? page.body).trim() ? "\n\n" : ""}${append}`;
    let unknown = [];
    const given = record(args, "fields");
    if (given) {
      const mapped = mapFieldValues(effectiveFields(page, type), given);
      unknown = mapped.unknown;
      patch.fields = { ...page.fields, ...mapped.values };
    }
    const tags = strings(args, "tags");
    if (tags) patch.tags = tags;
    await take(db.from("pages").update(patch).eq("id", page.id).select());
    return {
      updated: { id: page.id, title: patch.title ?? page.title },
      changed: Object.keys(patch).filter((k) => k !== "updated"),
      ...unknown.length ? { warning: `These named no field on this page and were not written: ${unknown.join(", ")}.` } : {}
    };
  }
};
var linkPages = {
  name: "link_pages",
  title: "Link two pages",
  description: "Draw a link from one page to another, the same link dragging between two cards makes. Direction matters: the board reads it as containment, so link a region to the settlements inside it, not the other way.",
  inputSchema: {
    type: "object",
    properties: {
      from: { type: "string", description: "The page the link starts at, by title or id." },
      to: { type: "string", description: "The page it points at, by title or id." },
      project: { type: "string", description: "Project name or id. Optional when there is only one." }
    },
    required: ["from", "to"]
  },
  writes: true,
  run: async (db, args) => {
    const project = await resolveProject(db, args);
    const from = await resolvePage(db, project.id, str(args, "from"));
    const to = await resolvePage(db, project.id, str(args, "to"));
    if (from.id === to.id) throw new ToolError("A page cannot link to itself.");
    const existing = await take(
      db.from("edges").select("*").eq("project_id", project.id).eq("from_page", from.id).eq("to_page", to.id)
    );
    if (existing.length) return { alreadyLinked: { from: from.title, to: to.title } };
    const row = {
      id: newId("e"),
      project_id: project.id,
      from_page: from.id,
      to_page: to.id,
      kind: "manual",
      updated: now()
    };
    await take(db.from("edges").insert(row).select());
    return { linked: { from: from.title, to: to.title } };
  }
};
var createBoard = {
  name: "create_board",
  title: "Create a board",
  description: "Add a board to an area. A board is one subject and one canvas; pages live on boards, never on areas.",
  inputSchema: {
    type: "object",
    properties: {
      name: { type: "string", description: "The board name." },
      area: { type: "string", description: "Area name or id to put it in." },
      project: { type: "string", description: "Project name or id. Optional when there is only one." }
    },
    required: ["name", "area"]
  },
  writes: true,
  run: async (db, args) => {
    const project = await resolveProject(db, args);
    const areas = await take(db.from("areas").select("*").eq("project_id", project.id));
    const wanted = str(args, "area");
    const area = areas.find((a) => a.id === wanted) ?? areas.find((a) => a.name.toLowerCase() === wanted.toLowerCase()) ?? areas.find((a) => a.name.toLowerCase().includes(wanted.toLowerCase()));
    if (!area) {
      throw new ToolError(`No area called "${wanted}". There is: ${areas.map((a) => a.name).join(", ")}.`);
    }
    const row = {
      id: newId("b"),
      project_id: project.id,
      area_id: area.id,
      name: str(args, "name"),
      updated: now()
    };
    await take(db.from("boards").insert(row).select());
    return { created: { id: row.id, name: row.name, area: area.name } };
  }
};
var createArea = {
  name: "create_area",
  title: "Create an area",
  description: "Add an area \u2014 a category such as Locations, NPCs or Rules \u2014 together with its first board, since an area with no board has nowhere to put a page.",
  inputSchema: {
    type: "object",
    properties: {
      name: { type: "string", description: "The area name." },
      board: { type: "string", description: "Name for its first board. Defaults to the area name." },
      defaultType: { type: "string", description: "Block type new pages default to here." },
      project: { type: "string", description: "Project name or id. Optional when there is only one." }
    },
    required: ["name"]
  },
  writes: true,
  run: async (db, args) => {
    const project = await resolveProject(db, args);
    const name = str(args, "name");
    const area = {
      id: newId("a"),
      project_id: project.id,
      name,
      default_type: resolveType(project, optionalStr(args, "defaultType")),
      updated: now()
    };
    await take(db.from("areas").insert(area).select());
    const board = {
      id: newId("b"),
      project_id: project.id,
      area_id: area.id,
      name: optionalStr(args, "board") ?? name,
      updated: now()
    };
    await take(db.from("boards").insert(board).select());
    return { created: { area: area.name, board: board.name, boardId: board.id } };
  }
};
var TOOLS = [
  listProjects,
  describeProject,
  listPages,
  readPage,
  searchPages,
  createPage,
  updatePage,
  linkPages,
  createBoard,
  createArea
];

// src/info.ts
var SERVER_INFO = { name: "cartographer", version: "0.1.0" };

// src/http/rpc.ts
var PROTOCOL_VERSION = "2025-06-18";
var ok = (id, result) => ({ jsonrpc: "2.0", id, result });
var fail = (id, code, message) => ({ jsonrpc: "2.0", id, error: { code, message } });
async function handleRpc(message, db, options) {
  const id = message.id ?? null;
  const tools = TOOLS.filter((t) => options.allowWrites || !t.writes);
  switch (message.method) {
    case "initialize":
      return ok(id, {
        protocolVersion: PROTOCOL_VERSION,
        capabilities: { tools: { listChanged: false } },
        serverInfo: SERVER_INFO,
        instructions: "Cartographer holds a tabletop or board-game project as areas, boards and pages. Call describe_project first: it returns the areas, the boards inside them, the block types with the fields each defines, and the tags in use, which is everything the other tools need. Name pages by title and fields by their labels."
      });
    // Notifications: acknowledged by saying nothing, which is what the spec asks.
    case "notifications/initialized":
    case "notifications/cancelled":
      return null;
    case "ping":
      return ok(id, {});
    case "tools/list":
      return ok(id, {
        tools: tools.map((t) => ({
          name: t.name,
          title: t.title,
          description: t.description,
          inputSchema: t.inputSchema,
          annotations: { readOnlyHint: !t.writes }
        }))
      });
    case "tools/call": {
      const name = String(message.params?.["name"] ?? "");
      const tool = tools.find((t) => t.name === name);
      if (!tool) {
        return ok(id, {
          isError: true,
          content: [{ type: "text", text: `No tool called "${name}".` }]
        });
      }
      try {
        const args = message.params?.["arguments"] ?? {};
        const result = await tool.run(db, args);
        return ok(id, { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] });
      } catch (e) {
        const text = e instanceof ToolError ? e.message : e instanceof Error ? e.message : String(e);
        return ok(id, { isError: true, content: [{ type: "text", text }] });
      }
    }
    default:
      return fail(id, -32601, `Unknown method "${message.method}".`);
  }
}

// src/http/signin.ts
function signInPage(options) {
  const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  const hidden = Object.entries(options.hidden).map(([k, v]) => `<input type="hidden" name="${esc(k)}" value="${esc(v)}">`).join("");
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Connect Cartographer</title>
<style>
  :root { color-scheme: dark light; }
  body {
    margin: 0; min-height: 100vh; display: grid; place-items: center;
    background: #0d1117; color: #e6edf3;
    font: 400 15px/1.5 ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
  }
  .card { width: min(380px, calc(100vw - 32px)); padding: 28px; }
  .kicker {
    font: 600 10px ui-monospace, SFMono-Regular, monospace; letter-spacing: .18em;
    text-transform: uppercase; color: #7d8590; margin-bottom: 10px;
  }
  h1 { margin: 0 0 6px; font-size: 21px; font-weight: 600; }
  p { margin: 0 0 20px; color: #9198a1; font-size: 13.5px; }
  label { display: block; margin-bottom: 14px; font: 600 10px ui-monospace, monospace;
          letter-spacing: .1em; text-transform: uppercase; color: #7d8590; }
  input[type=email], input[type=password] {
    display: block; width: 100%; box-sizing: border-box; margin-top: 6px;
    padding: 9px 11px; border: 1px solid rgba(255,255,255,.14); border-radius: 6px;
    background: #161b23; color: #e6edf3; font-size: 14.5px;
  }
  input:focus { outline: 2px solid #d9a441; outline-offset: 1px; border-color: transparent; }
  button {
    width: 100%; margin-top: 4px; padding: 10px; border: none; border-radius: 6px;
    background: #d9a441; color: #14100a; cursor: pointer;
    font: 600 11px ui-monospace, monospace; letter-spacing: .12em; text-transform: uppercase;
  }
  button:hover { filter: brightness(1.08); }
  .error {
    margin: 0 0 16px; padding: 9px 11px; border-radius: 6px; font-size: 13px;
    background: rgba(220,80,80,.12); border: 1px solid rgba(220,80,80,.35); color: #ffb4ad;
  }
  .foot { margin: 18px 0 0; font-size: 12px; color: #6e7681; }
  @media (prefers-color-scheme: light) {
    body { background: #f6f7f9; color: #10141a; }
    input[type=email], input[type=password] { background: #fff; border-color: rgba(0,0,0,.15); color: #10141a; }
    p, label, .foot { color: #5c6570; }
  }
</style>
</head><body>
<main class="card">
  <div class="kicker">Cartographer</div>
  <h1>Connect to ${esc(options.clientName)}</h1>
  <p>Sign in to let it read and edit your projects. It sees only what your account can.</p>
  ${options.error ? `<div class="error">${esc(options.error)}</div>` : ""}
  <form method="post" action="${esc(options.action)}">
    ${hidden}
    <label>Email
      <input type="email" name="email" autocomplete="username" required autofocus>
    </label>
    <label>Password
      <input type="password" name="password" autocomplete="current-password" required>
    </label>
    <button type="submit">Allow access</button>
  </form>
  <p class="foot">
    If you only ever sign in with Google, set a password first:
    Supabase \u2192 Authentication \u2192 Users \u2192 your user \u2192 Send password recovery.
  </p>
</main>
</body></html>`;
}

// src/http/handler.ts
var JSON_HEADERS = { "content-type": "application/json" };
var CORS = {
  "access-control-allow-origin": "*",
  "access-control-allow-headers": "authorization, content-type, mcp-protocol-version",
  "access-control-allow-methods": "GET, POST, OPTIONS",
  "access-control-max-age": "86400"
};
var json = (body, status = 200, extra = {}) => new Response(JSON.stringify(body), { status, headers: { ...JSON_HEADERS, ...CORS, ...extra } });
var oauthError = (error, description, status = 400) => json({ error, error_description: description }, status);
function publicBase(env) {
  return env.MCP_PUBLIC_URL ? env.MCP_PUBLIC_URL.replace(/\/+$/, "") : null;
}
function route(request) {
  const path = new URL(request.url).pathname.replace(/\/+$/, "");
  if (path.includes("/.well-known/oauth-protected-resource")) {
    return "/.well-known/oauth-protected-resource";
  }
  if (path.includes("/.well-known/oauth-authorization-server") || path.includes("/.well-known/openid-configuration")) {
    return "/.well-known/oauth-authorization-server";
  }
  for (const candidate of ["/register", "/authorize", "/token", "/mcp"]) {
    if (path === candidate || path.endsWith(candidate)) return candidate;
  }
  return path;
}
function admin(env) {
  return createClient(env.SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function formOrJson(request) {
  const type = request.headers.get("content-type") ?? "";
  if (type.includes("application/json")) {
    const body = await request.json().catch(() => ({}));
    const out2 = {};
    for (const [k, v] of Object.entries(body)) {
      out2[k] = typeof v === "string" ? v : JSON.stringify(v);
    }
    return out2;
  }
  const form = await request.formData().catch(() => new FormData());
  const out = {};
  for (const [k, v] of form.entries()) out[k] = typeof v === "string" ? v : "";
  return out;
}
async function handler(request, env) {
  if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: CORS });
  const base = publicBase(env);
  if (!base) {
    return json({
      error: "server_misconfigured",
      error_description: "MCP_PUBLIC_URL is not set. It must be the full public URL of this function, e.g. https://YOUR-PROJECT.supabase.co/functions/v1/mcp \u2014 every address in the OAuth discovery documents is built from it. Set it with: supabase secrets set MCP_PUBLIC_URL=..."
    }, 500);
  }
  const path = route(request);
  switch (path) {
    case "/.well-known/oauth-protected-resource":
      return json(protectedResourceMetadata(base));
    case "/.well-known/oauth-authorization-server":
      return json(authorizationServerMetadata(base));
    case "/register":
      return register(request, env);
    case "/authorize":
      return authorize(request, env, base);
    case "/token":
      return token(request, env);
    case "/mcp":
      return mcp(request, env, base);
    default:
      return json({ error: "not_found", endpoints: ["/mcp", "/authorize", "/token", "/register"] }, 404);
  }
}
async function register(request, env) {
  if (request.method !== "POST") return oauthError("invalid_request", "POST required.", 405);
  const body = await request.json().catch(() => null);
  const uris = Array.isArray(body?.["redirect_uris"]) ? body["redirect_uris"].filter((u) => typeof u === "string") : [];
  if (!uris.length) return oauthError("invalid_client_metadata", "redirect_uris is required.");
  for (const uri of uris) {
    try {
      const parsed = new URL(uri);
      if (parsed.protocol !== "https:" && parsed.hostname !== "localhost" && parsed.hostname !== "127.0.0.1") {
        return oauthError("invalid_redirect_uri", `${uri} is not https.`);
      }
    } catch {
      return oauthError("invalid_redirect_uri", `${uri} is not a URL.`);
    }
  }
  const client = {
    client_id: randomToken(16),
    client_secret: randomToken(32),
    client_name: typeof body?.["client_name"] === "string" ? body["client_name"].slice(0, 120) : "MCP client",
    redirect_uris: uris
  };
  const { error } = await admin(env).from("mcp_clients").insert(client);
  if (error) return oauthError("server_error", error.message, 500);
  return json({
    client_id: client.client_id,
    client_secret: client.client_secret,
    client_name: client.client_name,
    redirect_uris: client.redirect_uris,
    token_endpoint_auth_method: "client_secret_post",
    grant_types: ["authorization_code"],
    response_types: ["code"]
  }, 201);
}
async function authorize(request, env, base) {
  const params = request.method === "POST" ? await formOrJson(request) : Object.fromEntries(new URL(request.url).searchParams);
  const clientId = params["client_id"] ?? "";
  const redirectUri = params["redirect_uri"] ?? "";
  const challenge = params["code_challenge"] ?? "";
  const method = params["code_challenge_method"] ?? "";
  const state = params["state"] ?? null;
  const db = admin(env);
  const { data: client } = await db.from("mcp_clients").select("*").eq("client_id", clientId).maybeSingle();
  if (!client) return oauthError("invalid_client", "Unknown client. Remove the connector and add it again.");
  if (!redirectAllowed(client.redirect_uris, redirectUri)) {
    return oauthError("invalid_request", "That redirect URI is not registered to this client.");
  }
  if (params["response_type"] !== "code") {
    return Response.redirect(redirectWithError(redirectUri, "unsupported_response_type", state), 302);
  }
  if (method !== "S256" || !challenge) {
    return Response.redirect(redirectWithError(redirectUri, "invalid_request", state), 302);
  }
  const carry = {
    response_type: "code",
    client_id: clientId,
    redirect_uri: redirectUri,
    code_challenge: challenge,
    code_challenge_method: method,
    ...state ? { state } : {}
  };
  const page = (error2) => new Response(
    signInPage({
      action: `${base}/authorize`,
      hidden: carry,
      clientName: client.client_name ?? "Claude",
      ...error2 ? { error: error2 } : {}
    }),
    // 200 even when re-showing with an error: this is a form to fill in again, not
    // an API refusal, and nothing should be prompted for credentials by the browser.
    { status: 200, headers: { "content-type": "text/html; charset=utf-8" } }
  );
  if (request.method !== "POST") return page();
  const email = params["email"] ?? "";
  const password = params["password"] ?? "";
  if (!email || !password) return page("Enter your email and password.");
  const auth = createClient(env.SUPABASE_URL, env.SUPABASE_ANON_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
  const { data: session, error } = await auth.auth.signInWithPassword({ email, password });
  if (error || !session.session) return page(error?.message ?? "Could not sign in.");
  try {
    await db.rpc("mcp_sweep_expired");
  } catch {
  }
  const code = randomToken(32);
  const { error: saveError } = await db.from("mcp_codes").insert({
    code,
    client_id: clientId,
    user_id: session.session.user.id,
    redirect_uri: redirectUri,
    code_challenge: challenge,
    refresh_token: session.session.refresh_token,
    access_token: session.session.access_token,
    access_expires: new Date((session.session.expires_at ?? 0) * 1e3).toISOString(),
    expires_at: new Date(Date.now() + CODE_TTL_SECONDS * 1e3).toISOString()
  });
  if (saveError) return page(saveError.message);
  return Response.redirect(redirectWithCode(redirectUri, code, state), 302);
}
async function token(request, env) {
  if (request.method !== "POST") return oauthError("invalid_request", "POST required.", 405);
  const params = await formOrJson(request);
  if (params["grant_type"] !== "authorization_code") {
    return oauthError("unsupported_grant_type", "Only authorization_code is supported.");
  }
  const db = admin(env);
  const code = params["code"] ?? "";
  const { data: row } = await db.from("mcp_codes").select("*").eq("code", code).maybeSingle();
  if (!row) return oauthError("invalid_grant", "That code is not valid.");
  const secret = params["client_secret"];
  if (secret) {
    const { data: client } = await db.from("mcp_clients").select("client_secret").eq("client_id", row.client_id).maybeSingle();
    if (!client || client.client_secret !== secret) {
      await db.from("mcp_codes").delete().eq("code", code);
      return oauthError("invalid_client", "Client authentication failed.");
    }
  }
  await db.from("mcp_codes").delete().eq("code", code);
  if (new Date(row.expires_at).getTime() < Date.now()) {
    return oauthError("invalid_grant", "That code has expired.");
  }
  if ((params["client_id"] ?? "") !== row.client_id) {
    return oauthError("invalid_grant", "That code was issued to another client.");
  }
  if ((params["redirect_uri"] ?? "") !== row.redirect_uri) {
    return oauthError("invalid_grant", "Redirect URI does not match the one the code was issued for.");
  }
  if (!await pkceMatches(row.code_challenge, params["code_verifier"] ?? "")) {
    return oauthError("invalid_grant", "PKCE verification failed.");
  }
  const access = randomToken(32);
  const { error } = await db.from("mcp_tokens").insert({
    token_hash: await sha256Base64Url(access),
    client_id: row.client_id,
    user_id: row.user_id,
    refresh_token: row.refresh_token,
    access_token: row.access_token ?? "",
    access_expires: row.access_expires ?? (/* @__PURE__ */ new Date(0)).toISOString(),
    expires_at: new Date(Date.now() + TOKEN_TTL_SECONDS * 1e3).toISOString()
  });
  if (error) return oauthError("server_error", error.message, 500);
  return json({
    access_token: access,
    token_type: "Bearer",
    expires_in: TOKEN_TTL_SECONDS,
    scope: "cartographer"
  }, 200, { "cache-control": "no-store" });
}
function unauthorized(base) {
  return json({ error: "unauthorized" }, 401, {
    "www-authenticate": `Bearer resource_metadata="${base}/.well-known/oauth-protected-resource"`
  });
}
var REFRESH_MARGIN_MS = 6e4;
async function userSession(env, db, row) {
  const token2 = (r) => typeof r["access_token"] === "string" && r["access_token"] ? r["access_token"] : null;
  const expiresAt = (r) => new Date(String(r["access_expires"])).getTime();
  const fresh = (r) => token2(r) && expiresAt(r) - REFRESH_MARGIN_MS > Date.now();
  const usable = (r) => token2(r) && expiresAt(r) > Date.now();
  if (fresh(row)) return token2(row);
  const refreshed = await refresh(env, db, row);
  if (refreshed) return refreshed;
  for (const wait of [120, 300]) {
    await new Promise((resolve) => setTimeout(resolve, wait));
    const { data: latest } = await db.from("mcp_tokens").select("*").eq("token_hash", row["token_hash"]).maybeSingle();
    if (latest && usable(latest)) return token2(latest);
  }
  return null;
}
async function refresh(env, db, row) {
  const auth = createClient(env.SUPABASE_URL, env.SUPABASE_ANON_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
  const { data, error } = await auth.auth.refreshSession({
    refresh_token: row["refresh_token"]
  });
  if (error || !data.session) return null;
  await db.from("mcp_tokens").update({
    refresh_token: data.session.refresh_token,
    access_token: data.session.access_token,
    access_expires: new Date((data.session.expires_at ?? 0) * 1e3).toISOString()
  }).eq("token_hash", row["token_hash"]);
  return data.session.access_token;
}
async function mcp(request, env, base) {
  if (request.method === "GET") return json({ error: "method_not_allowed" }, 405);
  if (request.method !== "POST") return json({ error: "method_not_allowed" }, 405);
  const bearer = (request.headers.get("authorization") ?? "").replace(/^Bearer\s+/i, "").trim();
  if (!bearer) return unauthorized(base);
  const db = admin(env);
  const { data: row } = await db.from("mcp_tokens").select("*").eq("token_hash", await sha256Base64Url(bearer)).maybeSingle();
  if (!row) return unauthorized(base);
  if (new Date(row.expires_at).getTime() < Date.now()) {
    await db.from("mcp_tokens").delete().eq("token_hash", row.token_hash);
    return unauthorized(base);
  }
  const session = await userSession(env, db, row);
  if (!session) return unauthorized(base);
  const asUser = createClient(env.SUPABASE_URL, env.SUPABASE_ANON_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
    global: { headers: { Authorization: `Bearer ${session}` } }
  });
  const body = await request.json().catch(() => null);
  if (!body) return json({ jsonrpc: "2.0", id: null, error: { code: -32700, message: "Parse error." } });
  const allowWrites = env.CARTOGRAPHER_READ_ONLY !== "1";
  const messages = Array.isArray(body) ? body : [body];
  const replies = [];
  for (const message of messages) {
    const reply = await handleRpc(message, asUser, { allowWrites });
    if (reply) replies.push(reply);
  }
  if (!replies.length) return new Response(null, { status: 202, headers: CORS });
  return json(Array.isArray(body) ? replies : replies[0]);
}
export {
  handler
};
