/**
 * Cartographer's hosted connector, as a Supabase Edge Function.
 *
 * All the logic lives in the mcp package as a plain web handler — Request in,
 * Response out — so it is the same code whether it runs here, on a Worker, or
 * under test on Node. This file only supplies the environment and the listener.
 *
 * Deploy with:
 *   supabase functions deploy mcp --no-verify-jwt
 *
 * --no-verify-jwt matters: this function does its own OAuth, and the platform's
 * built-in JWT check would reject the discovery and token requests that have to be
 * reachable before anyone has a token at all.
 */
// handler.js is generated by `npm run bundle` in the mcp package. Supabase deploys
// only what lives under supabase/functions, so the code has to be a file here
// rather than an import from elsewhere in the repo.
// @ts-expect-error — a Deno-resolved module, not part of this repo's tsconfig.
import { handler } from './handler.js';

// @ts-expect-error — Deno's global, absent from the app's DOM/Node typings.
Deno.serve((request: Request) => handler(request, Deno.env.toObject()));
